language: cpp

compiler:
- gcc

jobs:
  include:
  - name: "all projects"

services:
- docker<ESC>
script:
    - cmake -H. -B_build
    - cmake --build _build
    - docker build -t logger .<ESC>
:wq


addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
